class Dashboard
{
    FileUpload()
    {
        
        
        cy.get('skin-atlas')
            .shadow()
            .find('.wrapper')
            .find('#main')
            .find('private-component')
            .find('dashboard-view')
            .shadow()
            .find('.main-content')
            .find('div')
            .find('.row')
            .find('.col')
            .find('classifier-performance')
            .shadow()
            .find('classifier-performance-table')
            .shadow()
            .find('table-with-action-bar')
            .find('div')
            .find('md-button')
            .shadow()
            .find('.md-button')
            .click()

        cy.get('skin-atlas')
            .shadow()
            .find('.wrapper')
            .find('#main')
            .find('private-component')
            .find('dashboard-view')
            .shadow()
            .find('.main-content')
            .find('div')
            .find('.row')
            .find('.graph-container')
            .find('classifier-performance')
            .shadow()
            .find('classifier-performance-table')
            .shadow()
            .find('file-upload-dialog')
            .shadow()
            .find('md-dialog')
            .find('vaadin-upload')
            .find('.cursor-pointer')
            .find('.btn-upload')
            .attachFile('classifier-performance-summary.csv', { subjectType: 'drag-n-drop' })
            

        cy.get('skin-atlas')
            .shadow()
            .find('.wrapper')
            .find('#main')
            .find('private-component')
            .find('dashboard-view')
            .shadow()
            .find('.main-content')
            .find('div')
            .find('.row')
            .find('.graph-container')
            .find('classifier-performance')
            .shadow()
            .find('classifier-performance-table')
            .shadow()
            .find('file-upload-dialog')
            .shadow()
            .find('md-dialog')
            .shadow()
            .find('paper-dialog')
            .find('.buttons-wrapper')
            .find('md-button')
            .shadow()
            .find('.md-button')
            .eq('1')
            .click()
    }

    UploadAssertion()
    {
        cy.get('skin-atlas')
            .shadow()
            .find('.wrapper')
            .find('#main')
            .find('private-component')
            .find('dashboard-view')
            .shadow()
            .find('.main-content')
            .find('div')
            .find('.row')
            .find('.graph-container')
            .find('classifier-performance')
            .shadow()
            .find('classifier-performance-table')
            .shadow()
            .find('table-with-action-bar')
            .shadow()
            .find('.table-wrapper')
            .find('md-table')
            .shadow()
            .find('.table-wrapper')
            .find('table')
            .find('tr')
            .eq('0')
            .find('th')
            .eq('0')
            .find('.th-content')
            .find('span')
            .eq('0')
            .contains('Drug Type')
    }

}

export default Dashboard