class Informatics
{
    InformaticsPage()
    {
        cy.get('skin-atlas')
            .shadow()
            .find('.wrapper')
            .find('#main')
            .find('private-component')
            .shadow()
            .find('side-bar')
            .shadow()
            .find('.sidebar-main-wrapper')
            .find('.sidebar-inner-wrapper')
            .find('.menu-item')
            .eq('1')
            .click()
        cy.waitUntil(() => 
        cy.get('skin-atlas')
            .shadow()
            .find('.wrapper')
            .find('#main')
            .find('private-component')
            .find('informatics-view')
            .shadow()
            .find('nav-bar')
            .shadow()
            .find('.navbar-wrapper')
            .find('.nav-bar-title')
            .contains('Informatics'), {

            errorMsg: 'Could not find title', // overrides the default error message
            timeout: 3000, // waits up to 2000 ms, default to 5000
            interval: 500 // performs the check every 500 ms, default to 200
            });
    }
    FilterByAge()
    {
        // cy.get('skin-atlas')
        //     .shadow()
        //     .find('.wrapper')
        //     .find('#main')
        //     .find('private-component')
        //     .find('informatics-view')
        //     .shadow()
        //     .find('.main-content')
        //     .find('md-tabs')
        //     .shadow()
        //     .find('iron-pages')
        //     .find('.iron-selected')
        //     .find('clinical-trial')
        //     .shadow()
        //     .find('clinical-trial-chart')
        //     .shadow()
        //     .find('.row')
        //     .find('.graph-container')
        //     .find('md-chart')
        //     .shadow()
        //     .find('.chart-main-wrapper')
        //     .find('.relative')
        //     .find('.bar-chart-container')
        //     .find('resize-observer-container')
        //     .find('google-chart')
        //     .shadow()
        //     .find('#chartdiv')
        //     .find('div')
        //     .find('div')
        //     .find('div')
        //     .wait(3000)
        //     .find('svg')
            
        //     .find('g')
        //     .eq('1')
        //     .find('g')
        //     .eq('0')
        //     .wait(2000)
        //     .find('g')
            
        //     .find('rect')
        //     .eq('0')
        //     .click()
    }


    FilterBySite()
    {
        //Click Dropdown Icon
        cy.get('skin-atlas')
            .shadow()
            .find('.wrapper')
            .find('#main')
            .find('private-component')
            .find('informatics-view')
            .shadow()
            .find('.main-content')
            .find('md-tabs')
            .shadow()
            .find('iron-pages')
            .find('.iron-selected')
            .find('clinical-trial')
            .shadow()
            .find('clinical-trial-chart')
            .shadow()
            .find('.row')
            .find('.col')
            .eq('4')
            .find('md-chart')
            .find('div')
            .find('site-filter')
            .shadow()
            .find('filter-dropdown')
            .shadow()
            .find('.filter-dropdown')
            .click()

        //Select option from drop down list
        cy.get('skin-atlas')
            .shadow()
            .find('.wrapper')
            .find('#main')
            .find('private-component')
            .find('informatics-view')
            .shadow()
            .find('.main-content')
            .find('md-tabs')
            .shadow()
            .find('iron-pages')
            .find('.iron-selected')
            .find('clinical-trial')
            .shadow()
            .find('clinical-trial-chart')
            .shadow()
            .find('.row')
            .find('.col')
            .eq('4')
            .find('md-chart')
            .find('div')
            .find('site-filter')
            .shadow()
            .find('filter-dropdown')
            .shadow()
            .find('#filter-menu')
            .find('.filter-menu-list')
            .find('mwc-list-item')
            .eq('1')
            .click()
        
    }

    FilterProject()
    {
        //Click Pyramid icon
        cy.get('skin-atlas')
            .shadow()
            .find('.wrapper')
            .find('#main')
            .find('private-component')
            .find('informatics-view')
            .shadow()
            .find('.main-content')
            .find('md-tabs')
            .shadow()
            .find('iron-pages')
            .find('.iron-selected')
            .find('clinical-trial')
            .shadow()
            .find('#edc-table')
            .find('edc-information-table')
            .shadow()
            .find('div')
            .find('table-with-action-bar')
            .shadow()
            .find('.table-wrapper')
            .find('md-table')
            .shadow()
            .find('.table-wrapper')
            .find('table')
            .find('tr')
            .eq('0')
            .find('th')
            .eq('1')
            .find('.th-content')
            .find('span')
            .eq('1')
            .find('mwc-icon-button')
            .shadow()
            .find('.mdc-ripple-upgraded--unbounded')
            .find('.material-icons')
            .click()



        //Type project name in input field
        cy.get('skin-atlas')
            .shadow()
            .find('.wrapper')
            .find('#main')
            .find('private-component')
            .find('informatics-view')
            .shadow()
            .find('.main-content')
            .find('md-tabs')
            .shadow()
            .find('iron-pages')
            .find('.iron-selected')
            .find('clinical-trial')
            .shadow()
            .find('#edc-table')
            .find('edc-information-table')
            .shadow()
            .find('div')
            .find('table-with-action-bar')
            .shadow()
            .find('.table-wrapper')
            .find('md-table')
            .shadow()
            .find('.table-wrapper')
            .find('#filter-menu')
            .find('filter-capsule')
            .shadow()
            .find('.dropdown-wrapper')
            .find('min-auto-complete')
            .shadow()
            .find('#autocomplete-wrapper')
            .find('.align-items-center')
            .find('.select-control-wrap')
            .find('.editable-input-container')
            .find('#input')
            .type('STAMP-1')

        //Click option from drop down list
        cy.get('skin-atlas')
            .shadow()
            .find('.wrapper')
            .find('#main')
            .find('private-component')
            .find('informatics-view')
            .shadow()
            .find('.main-content')
            .find('md-tabs')
            .shadow()
            .find('iron-pages')
            .find('.iron-selected')
            .find('clinical-trial')
            .shadow()
            .find('#edc-table')
            .find('edc-information-table')
            .shadow()
            .find('div')
            .find('table-with-action-bar')
            .shadow()
            .find('.table-wrapper')
            .find('md-table')
            .shadow()
            .find('.table-wrapper')
            .find('#filter-menu')
            .find('filter-capsule')
            .shadow()
            .find('.dropdown-wrapper')
            .find('min-auto-complete')
            .shadow()
            .find('#autocomplete-wrapper')
            .find('div')
            .find('iron-dropdown')
            .find('mwc-list')
            .find('mwc-list-item')
            .eq('0')
            .click({forcce:true})

        
        //Click Apply Button
        cy.get('skin-atlas')
            .shadow()
            .find('.wrapper')
            .find('#main')
            .find('private-component')
            .find('informatics-view')
            .shadow()
            .find('.main-content')
            .find('md-tabs')
            .shadow()
            .find('iron-pages')
            .find('.iron-selected')
            .find('clinical-trial')
            .shadow()
            .find('#edc-table')
            .find('edc-information-table')
            .shadow()
            .find('div')
            .find('table-with-action-bar')
            .shadow()
            .find('.table-wrapper')
            .find('md-table')
            .shadow()
            .find('.table-wrapper')
            .find('#filter-menu')
            .find('filter-capsule')
            .shadow()
            .find('.button-wrapper')
            .find('.apply')
            .click()     
    }
    FilterSubjectID()
    {
        //Click Pyramid icon
        cy.get('skin-atlas')
            .shadow()
            .find('.wrapper')
            .find('#main')
            .find('private-component')
            .find('informatics-view')
            .shadow()
            .find('.main-content')
            .find('md-tabs')
            .shadow()
            .find('iron-pages')
            .find('.iron-selected')
            .find('clinical-trial')
            .shadow()
            .find('#edc-table')
            .find('edc-information-table')
            .shadow()
            .find('div')
            .find('table-with-action-bar')
            .shadow()
            .find('.table-wrapper')
            .find('md-table')
            .shadow()
            .find('.table-wrapper')
            .find('table')
            .find('tr')
            .eq('0')
            .find('th')
            .eq('2')
            .find('.th-content')
            .find('span')
            .eq('1')
            .find('mwc-icon-button')
            .shadow()
            .find('.mdc-ripple-upgraded--unbounded')
            .find('.material-icons')
            .click()



        //Type SubjectID in input field
        cy.get('skin-atlas')
            .shadow()
            .find('.wrapper')
            .find('#main')
            .find('private-component')
            .find('informatics-view')
            .shadow()
            .find('.main-content')
            .find('md-tabs')
            .shadow()
            .find('iron-pages')
            .find('.iron-selected')
            .find('clinical-trial')
            .shadow()
            .find('#edc-table')
            .find('edc-information-table')
            .shadow()
            .find('div')
            .find('table-with-action-bar')
            .shadow()
            .find('.table-wrapper')
            .find('md-table')
            .shadow()
            .find('.table-wrapper')
            .find('#filter-menu')
            .find('filter-capsule')
            .shadow()
            .find('.dropdown-wrapper')
            .find('min-auto-complete')
            .shadow()
            .find('#autocomplete-wrapper')
            .find('.align-items-center')
            .find('.select-control-wrap')
            .find('.editable-input-container')
            .find('#input')
            .type('SITE001-0001')

        //Click option from drop down list
        cy.get('skin-atlas')
            .shadow()
            .find('.wrapper')
            .find('#main')
            .find('private-component')
            .find('informatics-view')
            .shadow()
            .find('.main-content')
            .find('md-tabs')
            .shadow()
            .find('iron-pages')
            .find('.iron-selected')
            .find('clinical-trial')
            .shadow()
            .find('#edc-table')
            .find('edc-information-table')
            .shadow()
            .find('div')
            .find('table-with-action-bar')
            .shadow()
            .find('.table-wrapper')
            .find('md-table')
            .shadow()
            .find('.table-wrapper')
            .find('#filter-menu')
            .find('filter-capsule')
            .shadow()
            .find('.dropdown-wrapper')
            .find('min-auto-complete')
            .shadow()
            .find('#autocomplete-wrapper')
            .find('div')
            .find('iron-dropdown')
            .find('mwc-list')
            .find('mwc-list-item')
            .eq('0')
            .click({forcce:true})

        
        //Click Apply Button
        cy.get('skin-atlas')
            .shadow()
            .find('.wrapper')
            .find('#main')
            .find('private-component')
            .find('informatics-view')
            .shadow()
            .find('.main-content')
            .find('md-tabs')
            .shadow()
            .find('iron-pages')
            .find('.iron-selected')
            .find('clinical-trial')
            .shadow()
            .find('#edc-table')
            .find('edc-information-table')
            .shadow()
            .find('div')
            .find('table-with-action-bar')
            .shadow()
            .find('.table-wrapper')
            .find('md-table')
            .shadow()
            .find('.table-wrapper')
            .find('#filter-menu')
            .find('filter-capsule')
            .shadow()
            .find('.button-wrapper')
            .find('.apply')
            .click()

    }
    FilterDrug()
    {
        //Click Pyramid icon
        cy.get('skin-atlas')
            .shadow()
            .find('.wrapper')
            .find('#main')
            .find('private-component')
            .find('informatics-view')
            .shadow()
            .find('.main-content')
            .find('md-tabs')
            .shadow()
            .find('iron-pages')
            .find('.iron-selected')
            .find('clinical-trial')
            .shadow()
            .find('#edc-table')
            .find('edc-information-table')
            .shadow()
            .find('div')
            .find('table-with-action-bar')
            .shadow()
            .find('.table-wrapper')
            .find('md-table')
            .shadow()
            .find('.table-wrapper')
            .find('table')
            .find('tr')
            .eq('0')
            .find('th')
            .eq('3')
            .find('.th-content')
            .find('span')
            .eq('1')
            .find('mwc-icon-button')
            .shadow()
            .find('.mdc-ripple-upgraded--unbounded')
            .find('.material-icons')
            .click()



        //Type SubjectID in input field
        cy.get('skin-atlas')
            .shadow()
            .find('.wrapper')
            .find('#main')
            .find('private-component')
            .find('informatics-view')
            .shadow()
            .find('.main-content')
            .find('md-tabs')
            .shadow()
            .find('iron-pages')
            .find('.iron-selected')
            .find('clinical-trial')
            .shadow()
            .find('#edc-table')
            .find('edc-information-table')
            .shadow()
            .find('div')
            .find('table-with-action-bar')
            .shadow()
            .find('.table-wrapper')
            .find('md-table')
            .shadow()
            .find('.table-wrapper')
            .find('#filter-menu')
            .find('filter-capsule')
            .shadow()
            .find('.dropdown-wrapper')
            .find('min-auto-complete')
            .shadow()
            .find('#autocomplete-wrapper')
            .find('.align-items-center')
            .find('.select-control-wrap')
            .find('.editable-input-container')
            .find('#input')
            .type('Risankizumab')

        //Click option from drop down list
        cy.get('skin-atlas')
            .shadow()
            .find('.wrapper')
            .find('#main')
            .find('private-component')
            .find('informatics-view')
            .shadow()
            .find('.main-content')
            .find('md-tabs')
            .shadow()
            .find('iron-pages')
            .find('.iron-selected')
            .find('clinical-trial')
            .shadow()
            .find('#edc-table')
            .find('edc-information-table')
            .shadow()
            .find('div')
            .find('table-with-action-bar')
            .shadow()
            .find('.table-wrapper')
            .find('md-table')
            .shadow()
            .find('.table-wrapper')
            .find('#filter-menu')
            .find('filter-capsule')
            .shadow()
            .find('.dropdown-wrapper')
            .find('min-auto-complete')
            .shadow()
            .find('#autocomplete-wrapper')
            .find('div')
            .find('iron-dropdown')
            .find('mwc-list')
            .find('mwc-list-item')
            .eq('0')
            .click({forcce:true})

        
        //Click Apply Button
        cy.get('skin-atlas')
            .shadow()
            .find('.wrapper')
            .find('#main')
            .find('private-component')
            .find('informatics-view')
            .shadow()
            .find('.main-content')
            .find('md-tabs')
            .shadow()
            .find('iron-pages')
            .find('.iron-selected')
            .find('clinical-trial')
            .shadow()
            .find('#edc-table')
            .find('edc-information-table')
            .shadow()
            .find('div')
            .find('table-with-action-bar')
            .shadow()
            .find('.table-wrapper')
            .find('md-table')
            .shadow()
            .find('.table-wrapper')
            .find('#filter-menu')
            .find('filter-capsule')
            .shadow()
            .find('.button-wrapper')
            .find('.apply')
            .click()

    }

    FilterDrugClass()
    {
        //Click Pyramid icon
        cy.get('skin-atlas')
            .shadow()
            .find('.wrapper')
            .find('#main')
            .find('private-component')
            .find('informatics-view')
            .shadow()
            .find('.main-content')
            .find('md-tabs')
            .shadow()
            .find('iron-pages')
            .find('.iron-selected')
            .find('clinical-trial')
            .shadow()
            .find('#edc-table')
            .find('edc-information-table')
            .shadow()
            .find('div')
            .find('table-with-action-bar')
            .shadow()
            .find('.table-wrapper')
            .find('md-table')
            .shadow()
            .find('.table-wrapper')
            .find('table')
            .find('tr')
            .eq('0')
            .find('th')
            .eq('4')
            .find('.th-content')
            .find('span')
            .eq('1')
            .find('mwc-icon-button')
            .shadow()
            .find('.mdc-ripple-upgraded--unbounded')
            .find('.material-icons')
            .scrollIntoView()
            .click()



        //Type Drugclass in input field
        cy.get('skin-atlas')
            .shadow()
            .find('.wrapper')
            .find('#main')
            .find('private-component')
            .find('informatics-view')
            .shadow()
            .find('.main-content')
            .find('md-tabs')
            .shadow()
            .find('iron-pages')
            .find('.iron-selected')
            .find('clinical-trial')
            .shadow()
            .find('#edc-table')
            .find('edc-information-table')
            .shadow()
            .find('div')
            .find('table-with-action-bar')
            .shadow()
            .find('.table-wrapper')
            .find('md-table')
            .shadow()
            .find('.table-wrapper')
            .find('#filter-menu')
            .find('filter-capsule')
            .shadow()
            .find('.dropdown-wrapper')
            .find('min-auto-complete')
            .shadow()
            .find('#autocomplete-wrapper')
            .find('.align-items-center')
            .find('.select-control-wrap')
            .find('.editable-input-container')
            .find('#input')
            .type('anti-il-23')

        //Click option from drop down list
        cy.get('skin-atlas')
            .shadow()
            .find('.wrapper')
            .find('#main')
            .find('private-component')
            .find('informatics-view')
            .shadow()
            .find('.main-content')
            .find('md-tabs')
            .shadow()
            .find('iron-pages')
            .find('.iron-selected')
            .find('clinical-trial')
            .shadow()
            .find('#edc-table')
            .find('edc-information-table')
            .shadow()
            .find('div')
            .find('table-with-action-bar')
            .shadow()
            .find('.table-wrapper')
            .find('md-table')
            .shadow()
            .find('.table-wrapper')
            .find('#filter-menu')
            .find('filter-capsule')
            .shadow()
            .find('.dropdown-wrapper')
            .find('min-auto-complete')
            .shadow()
            .find('#autocomplete-wrapper')
            .find('div')
            .find('iron-dropdown')
            .find('mwc-list')
            .find('mwc-list-item')
            .eq('0')
            .click({forcce:true})

        
        //Click Apply Button
        cy.get('skin-atlas')
            .shadow()
            .find('.wrapper')
            .find('#main')
            .find('private-component')
            .find('informatics-view')
            .shadow()
            .find('.main-content')
            .find('md-tabs')
            .shadow()
            .find('iron-pages')
            .find('.iron-selected')
            .find('clinical-trial')
            .shadow()
            .find('#edc-table')
            .find('edc-information-table')
            .shadow()
            .find('div')
            .find('table-with-action-bar')
            .shadow()
            .find('.table-wrapper')
            .find('md-table')
            .shadow()
            .find('.table-wrapper')
            .find('#filter-menu')
            .find('filter-capsule')
            .shadow()
            .find('.button-wrapper')
            .find('.apply')
            .click()

    }
    FilterAge()
    {
        //Click Pyramid icon
        cy.get('skin-atlas')
            .shadow()
            .find('.wrapper')
            .find('#main')
            .find('private-component')
            .find('informatics-view')
            .shadow()
            .find('.main-content')
            .find('md-tabs')
            .shadow()
            .find('iron-pages')
            .find('.iron-selected')
            .find('clinical-trial')
            .shadow()
            .find('#edc-table')
            .find('edc-information-table')
            .shadow()
            .find('div')
            .find('table-with-action-bar')
            .shadow()
            .find('.table-wrapper')
            .find('md-table')
            .shadow()
            .find('.table-wrapper')
            .find('table')
            .find('tr')
            .eq('0')
            .find('th')
            .eq('5')
            .find('.th-content')
            .find('span')
            .eq('1')
            .find('mwc-icon-button')
            .shadow()
            .find('.mdc-ripple-upgraded--unbounded')
            .find('.material-icons')
            .scrollIntoView()
            .click()



        //Type Age in input field
        cy.get('skin-atlas')
            .shadow()
            .find('.wrapper')
            .find('#main')
            .find('private-component')
            .find('informatics-view')
            .shadow()
            .find('.main-content')
            .find('md-tabs')
            .shadow()
            .find('iron-pages')
            .find('.iron-selected')
            .find('clinical-trial')
            .shadow()
            .find('#edc-table')
            .find('edc-information-table')
            .shadow()
            .find('div')
            .find('table-with-action-bar')
            .shadow()
            .find('.table-wrapper')
            .find('md-table')
            .shadow()
            .find('.table-wrapper')
            .find('#filter-menu')
            .find('filter-capsule')
            .shadow()
            .find('.dropdown-wrapper')
            .find('min-input')
            .shadow()
            .find('.form-group')
            .find('.form-group__control-wrap')
            .find('.form-group__input-control')
            .type('56')

        
        
        //Click Apply Button
        cy.get('skin-atlas')
            .shadow()
            .find('.wrapper')
            .find('#main')
            .find('private-component')
            .find('informatics-view')
            .shadow()
            .find('.main-content')
            .find('md-tabs')
            .shadow()
            .find('iron-pages')
            .find('.iron-selected')
            .find('clinical-trial')
            .shadow()
            .find('#edc-table')
            .find('edc-information-table')
            .shadow()
            .find('div')
            .find('table-with-action-bar')
            .shadow()
            .find('.table-wrapper')
            .find('md-table')
            .shadow()
            .find('.table-wrapper')
            .find('#filter-menu')
            .find('filter-capsule')
            .shadow()
            .find('.button-wrapper')
            .find('.apply')
            .click()

    }
    FilterAgeGroup()
    {
        //Click Pyramid icon
        cy.get('skin-atlas')
            .shadow()
            .find('.wrapper')
            .find('#main')
            .find('private-component')
            .find('informatics-view')
            .shadow()
            .find('.main-content')
            .find('md-tabs')
            .shadow()
            .find('iron-pages')
            .find('.iron-selected')
            .find('clinical-trial')
            .shadow()
            .find('#edc-table')
            .find('edc-information-table')
            .shadow()
            .find('div')
            .find('table-with-action-bar')
            .shadow()
            .find('.table-wrapper')
            .find('md-table')
            .shadow()
            .find('.table-wrapper')
            .find('table')
            .find('tr')
            .eq('0')
            .find('th')
            .eq('6')
            .find('.th-content')
            .find('span')
            .eq('1')
            .find('mwc-icon-button')
            .shadow()
            .find('.mdc-ripple-upgraded--unbounded')
            .find('.material-icons')
            .scrollIntoView()
            .click()



        //Type AgeGroup in input field
        cy.get('skin-atlas')
            .shadow()
            .find('.wrapper')
            .find('#main')
            .find('private-component')
            .find('informatics-view')
            .shadow()
            .find('.main-content')
            .find('md-tabs')
            .shadow()
            .find('iron-pages')
            .find('.iron-selected')
            .find('clinical-trial')
            .shadow()
            .find('#edc-table')
            .find('edc-information-table')
            .shadow()
            .find('div')
            .find('table-with-action-bar')
            .shadow()
            .find('.table-wrapper')
            .find('md-table')
            .shadow()
            .find('.table-wrapper')
            .find('#filter-menu')
            .find('filter-capsule')
            .shadow()
            .find('.dropdown-wrapper')
            .find('min-auto-complete')
            .shadow()
            .find('#autocomplete-wrapper')
            .find('.align-items-center')
            .find('.select-control-wrap')
            .find('.editable-input-container')
            .find('#input')
            .type('50-60')

        //Click option from drop down list
        cy.get('skin-atlas')
            .shadow()
            .find('.wrapper')
            .find('#main')
            .find('private-component')
            .find('informatics-view')
            .shadow()
            .find('.main-content')
            .find('md-tabs')
            .shadow()
            .find('iron-pages')
            .find('.iron-selected')
            .find('clinical-trial')
            .shadow()
            .find('#edc-table')
            .find('edc-information-table')
            .shadow()
            .find('div')
            .find('table-with-action-bar')
            .shadow()
            .find('.table-wrapper')
            .find('md-table')
            .shadow()
            .find('.table-wrapper')
            .find('#filter-menu')
            .find('filter-capsule')
            .shadow()
            .find('.dropdown-wrapper')
            .find('min-auto-complete')
            .shadow()
            .find('#autocomplete-wrapper')
            .find('div')
            .find('iron-dropdown')
            .find('mwc-list')
            .find('mwc-list-item')
            .eq('0')
            .click({forcce:true})

        
        //Click Apply Button
        cy.get('skin-atlas')
            .shadow()
            .find('.wrapper')
            .find('#main')
            .find('private-component')
            .find('informatics-view')
            .shadow()
            .find('.main-content')
            .find('md-tabs')
            .shadow()
            .find('iron-pages')
            .find('.iron-selected')
            .find('clinical-trial')
            .shadow()
            .find('#edc-table')
            .find('edc-information-table')
            .shadow()
            .find('div')
            .find('table-with-action-bar')
            .shadow()
            .find('.table-wrapper')
            .find('md-table')
            .shadow()
            .find('.table-wrapper')
            .find('#filter-menu')
            .find('filter-capsule')
            .shadow()
            .find('.button-wrapper')
            .find('.apply')
            .click()

    }

    FilterGender()
    {
        //Click Pyramid icon
        cy.get('skin-atlas')
            .shadow()
            .find('.wrapper')
            .find('#main')
            .find('private-component')
            .find('informatics-view')
            .shadow()
            .find('.main-content')
            .find('md-tabs')
            .shadow()
            .find('iron-pages')
            .find('.iron-selected')
            .find('clinical-trial')
            .shadow()
            .find('#edc-table')
            .find('edc-information-table')
            .shadow()
            .find('div')
            .find('table-with-action-bar')
            .shadow()
            .find('.table-wrapper')
            .find('md-table')
            .shadow()
            .find('.table-wrapper')
            .find('table')
            .find('tr')
            .eq('0')
            .find('th')
            .eq('7')
            .find('.th-content')
            .find('span')
            .eq('1')
            .find('mwc-icon-button')
            .shadow()
            .find('.mdc-ripple-upgraded--unbounded')
            .find('.material-icons')
            .scrollIntoView()
            .click()



        //Type gender in input field
        cy.get('skin-atlas')
            .shadow()
            .find('.wrapper')
            .find('#main')
            .find('private-component')
            .find('informatics-view')
            .shadow()
            .find('.main-content')
            .find('md-tabs')
            .shadow()
            .find('iron-pages')
            .find('.iron-selected')
            .find('clinical-trial')
            .shadow()
            .find('#edc-table')
            .find('edc-information-table')
            .shadow()
            .find('div')
            .find('table-with-action-bar')
            .shadow()
            .find('.table-wrapper')
            .find('md-table')
            .shadow()
            .find('.table-wrapper')
            .find('#filter-menu')
            .find('filter-capsule')
            .shadow()
            .find('.dropdown-wrapper')
            .find('min-auto-complete')
            .shadow()
            .find('#autocomplete-wrapper')
            .find('.align-items-center')
            .find('.select-control-wrap')
            .find('.editable-input-container')
            .find('#input')
            .type('Male')

        //Click option from drop down list
        cy.get('skin-atlas')
            .shadow()
            .find('.wrapper')
            .find('#main')
            .find('private-component')
            .find('informatics-view')
            .shadow()
            .find('.main-content')
            .find('md-tabs')
            .shadow()
            .find('iron-pages')
            .find('.iron-selected')
            .find('clinical-trial')
            .shadow()
            .find('#edc-table')
            .find('edc-information-table')
            .shadow()
            .find('div')
            .find('table-with-action-bar')
            .shadow()
            .find('.table-wrapper')
            .find('md-table')
            .shadow()
            .find('.table-wrapper')
            .find('#filter-menu')
            .find('filter-capsule')
            .shadow()
            .find('.dropdown-wrapper')
            .find('min-auto-complete')
            .shadow()
            .find('#autocomplete-wrapper')
            .find('div')
            .find('iron-dropdown')
            .find('mwc-list')
            .find('mwc-list-item')
            .eq('1')
            .click({forcce:true})

        
        //Click Apply Button
        cy.get('skin-atlas')
            .shadow()
            .find('.wrapper')
            .find('#main')
            .find('private-component')
            .find('informatics-view')
            .shadow()
            .find('.main-content')
            .find('md-tabs')
            .shadow()
            .find('iron-pages')
            .find('.iron-selected')
            .find('clinical-trial')
            .shadow()
            .find('#edc-table')
            .find('edc-information-table')
            .shadow()
            .find('div')
            .find('table-with-action-bar')
            .shadow()
            .find('.table-wrapper')
            .find('md-table')
            .shadow()
            .find('.table-wrapper')
            .find('#filter-menu')
            .find('filter-capsule')
            .shadow()
            .find('.button-wrapper')
            .find('.apply')
            .click()

    }

    FilterBMI()
    {
        //Click Pyramid icon
        cy.get('skin-atlas')
            .shadow()
            .find('.wrapper')
            .find('#main')
            .find('private-component')
            .find('informatics-view')
            .shadow()
            .find('.main-content')
            .find('md-tabs')
            .shadow()
            .find('iron-pages')
            .find('.iron-selected')
            .find('clinical-trial')
            .shadow()
            .find('#edc-table')
            .find('edc-information-table')
            .shadow()
            .find('div')
            .find('table-with-action-bar')
            .shadow()
            .find('.table-wrapper')
            .find('md-table')
            .shadow()
            .find('.table-wrapper')
            .find('table')
            .find('tr')
            .eq('0')
            .find('th')
            .eq('8')
            .find('.th-content')
            .find('span')
            .eq('1')
            .find('mwc-icon-button')
            .shadow()
            .find('.mdc-ripple-upgraded--unbounded')
            .find('.material-icons')
            .scrollIntoView()
            .click()



        //Type BMI in input field
        cy.get('skin-atlas')
            .shadow()
            .find('.wrapper')
            .find('#main')
            .find('private-component')
            .find('informatics-view')
            .shadow()
            .find('.main-content')
            .find('md-tabs')
            .shadow()
            .find('iron-pages')
            .find('.iron-selected')
            .find('clinical-trial')
            .shadow()
            .find('#edc-table')
            .find('edc-information-table')
            .shadow()
            .find('div')
            .find('table-with-action-bar')
            .shadow()
            .find('.table-wrapper')
            .find('md-table')
            .shadow()
            .find('.table-wrapper')
            .find('#filter-menu')
            .find('filter-capsule')
            .shadow()
            .find('.dropdown-wrapper')
            .find('min-input')
            .shadow()
            .find('.form-group')
            .find('.form-group__control-wrap')
            .find('.form-group__input-control')
            .type('45.6859')


        

        
        //Click Apply Button
        cy.get('skin-atlas')
            .shadow()
            .find('.wrapper')
            .find('#main')
            .find('private-component')
            .find('informatics-view')
            .shadow()
            .find('.main-content')
            .find('md-tabs')
            .shadow()
            .find('iron-pages')
            .find('.iron-selected')
            .find('clinical-trial')
            .shadow()
            .find('#edc-table')
            .find('edc-information-table')
            .shadow()
            .find('div')
            .find('table-with-action-bar')
            .shadow()
            .find('.table-wrapper')
            .find('md-table')
            .shadow()
            .find('.table-wrapper')
            .find('#filter-menu')
            .find('filter-capsule')
            .shadow()
            .find('.button-wrapper')
            .find('.apply')
            .click()

    }

    FilterBMIGroup()
    {
        //Click Pyramid icon
        cy.get('skin-atlas')
            .shadow()
            .find('.wrapper')
            .find('#main')
            .find('private-component')
            .find('informatics-view')
            .shadow()
            .find('.main-content')
            .find('md-tabs')
            .shadow()
            .find('iron-pages')
            .find('.iron-selected')
            .find('clinical-trial')
            .shadow()
            .find('#edc-table')
            .find('edc-information-table')
            .shadow()
            .find('div')
            .find('table-with-action-bar')
            .shadow()
            .find('.table-wrapper')
            .find('md-table')
            .shadow()
            .find('.table-wrapper')
            .find('table')
            .find('tr')
            .eq('0')
            .find('th')
            .eq('9')
            .find('.th-content')
            .find('span')
            .eq('1')
            .find('mwc-icon-button')
            .shadow()
            .find('.mdc-ripple-upgraded--unbounded')
            .find('.material-icons')
            .scrollIntoView()
            .click()



        //Type BMIGroup in input field
        cy.get('skin-atlas')
            .shadow()
            .find('.wrapper')
            .find('#main')
            .find('private-component')
            .find('informatics-view')
            .shadow()
            .find('.main-content')
            .find('md-tabs')
            .shadow()
            .find('iron-pages')
            .find('.iron-selected')
            .find('clinical-trial')
            .shadow()
            .find('#edc-table')
            .find('edc-information-table')
            .shadow()
            .find('div')
            .find('table-with-action-bar')
            .shadow()
            .find('.table-wrapper')
            .find('md-table')
            .shadow()
            .find('.table-wrapper')
            .find('#filter-menu')
            .find('filter-capsule')
            .shadow()
            .find('.dropdown-wrapper')
            .find('min-auto-complete')
            .shadow()
            .find('#autocomplete-wrapper')
            .find('.align-items-center')
            .find('.select-control-wrap')
            .find('.editable-input-container')
            .find('#input')
            .type('40+')

        //Click option from drop down list
        cy.get('skin-atlas')
            .shadow()
            .find('.wrapper')
            .find('#main')
            .find('private-component')
            .find('informatics-view')
            .shadow()
            .find('.main-content')
            .find('md-tabs')
            .shadow()
            .find('iron-pages')
            .find('.iron-selected')
            .find('clinical-trial')
            .shadow()
            .find('#edc-table')
            .find('edc-information-table')
            .shadow()
            .find('div')
            .find('table-with-action-bar')
            .shadow()
            .find('.table-wrapper')
            .find('md-table')
            .shadow()
            .find('.table-wrapper')
            .find('#filter-menu')
            .find('filter-capsule')
            .shadow()
            .find('.dropdown-wrapper')
            .find('min-auto-complete')
            .shadow()
            .find('#autocomplete-wrapper')
            .find('div')
            .find('iron-dropdown')
            .find('mwc-list')
            .find('mwc-list-item')
            .eq('0')
            .click({forcce:true})

        
        //Click Apply Button
        cy.get('skin-atlas')
            .shadow()
            .find('.wrapper')
            .find('#main')
            .find('private-component')
            .find('informatics-view')
            .shadow()
            .find('.main-content')
            .find('md-tabs')
            .shadow()
            .find('iron-pages')
            .find('.iron-selected')
            .find('clinical-trial')
            .shadow()
            .find('#edc-table')
            .find('edc-information-table')
            .shadow()
            .find('div')
            .find('table-with-action-bar')
            .shadow()
            .find('.table-wrapper')
            .find('md-table')
            .shadow()
            .find('.table-wrapper')
            .find('#filter-menu')
            .find('filter-capsule')
            .shadow()
            .find('.button-wrapper')
            .find('.apply')
            .click()

    }

    FilterWeight()
    {
        //Click Pyramid icon
        cy.get('skin-atlas')
            .shadow()
            .find('.wrapper')
            .find('#main')
            .find('private-component')
            .find('informatics-view')
            .shadow()
            .find('.main-content')
            .find('md-tabs')
            .shadow()
            .find('iron-pages')
            .find('.iron-selected')
            .find('clinical-trial')
            .shadow()
            .find('#edc-table')
            .find('edc-information-table')
            .shadow()
            .find('div')
            .find('table-with-action-bar')
            .shadow()
            .find('.table-wrapper')
            .find('md-table')
            .shadow()
            .find('.table-wrapper')
            .find('table')
            .find('tr')
            .eq('0')
            .find('th')
            .eq('10')
            .find('.th-content')
            .find('span')
            .eq('1')
            .find('mwc-icon-button')
            .shadow()
            .find('.mdc-ripple-upgraded--unbounded')
            .find('.material-icons')
            .scrollIntoView()
            .click()



        //Type weight in input field
        cy.get('skin-atlas')
            .shadow()
            .find('.wrapper')
            .find('#main')
            .find('private-component')
            .find('informatics-view')
            .shadow()
            .find('.main-content')
            .find('md-tabs')
            .shadow()
            .find('iron-pages')
            .find('.iron-selected')
            .find('clinical-trial')
            .shadow()
            .find('#edc-table')
            .find('edc-information-table')
            .shadow()
            .find('div')
            .find('table-with-action-bar')
            .shadow()
            .find('.table-wrapper')
            .find('md-table')
            .shadow()
            .find('.table-wrapper')
            .find('#filter-menu')
            .find('filter-capsule')
            .shadow()
            .find('.dropdown-wrapper')
            .find('min-input')
            .shadow()
            .find('.form-group')
            .find('.form-group__control-wrap')
            .find('.form-group__input-control')
            .type('327.6')


        
        
        //Click Apply Button
        cy.get('skin-atlas')
            .shadow()
            .find('.wrapper')
            .find('#main')
            .find('private-component')
            .find('informatics-view')
            .shadow()
            .find('.main-content')
            .find('md-tabs')
            .shadow()
            .find('iron-pages')
            .find('.iron-selected')
            .find('clinical-trial')
            .shadow()
            .find('#edc-table')
            .find('edc-information-table')
            .shadow()
            .find('div')
            .find('table-with-action-bar')
            .shadow()
            .find('.table-wrapper')
            .find('md-table')
            .shadow()
            .find('.table-wrapper')
            .find('#filter-menu')
            .find('filter-capsule')
            .shadow()
            .find('.button-wrapper')
            .find('.apply')
            .click()

    }
    FilterRace()
    {
        //Click Pyramid icon
        cy.get('skin-atlas')
            .shadow()
            .find('.wrapper')
            .find('#main')
            .find('private-component')
            .find('informatics-view')
            .shadow()
            .find('.main-content')
            .find('md-tabs')
            .shadow()
            .find('iron-pages')
            .find('.iron-selected')
            .find('clinical-trial')
            .shadow()
            .find('#edc-table')
            .find('edc-information-table')
            .shadow()
            .find('div')
            .find('table-with-action-bar')
            .shadow()
            .find('.table-wrapper')
            .find('md-table')
            .shadow()
            .find('.table-wrapper')
            .find('table')
            .find('tr')
            .eq('0')
            .find('th')
            .eq('11')
            .find('.th-content')
            .find('span')
            .eq('1')
            .find('mwc-icon-button')
            .shadow()
            .find('.mdc-ripple-upgraded--unbounded')
            .find('.material-icons')
            .scrollIntoView()
            .click()



        //Type Race in input field
        cy.get('skin-atlas')
            .shadow()
            .find('.wrapper')
            .find('#main')
            .find('private-component')
            .find('informatics-view')
            .shadow()
            .find('.main-content')
            .find('md-tabs')
            .shadow()
            .find('iron-pages')
            .find('.iron-selected')
            .find('clinical-trial')
            .shadow()
            .find('#edc-table')
            .find('edc-information-table')
            .shadow()
            .find('div')
            .find('table-with-action-bar')
            .shadow()
            .find('.table-wrapper')
            .find('md-table')
            .shadow()
            .find('.table-wrapper')
            .find('#filter-menu')
            .find('filter-capsule')
            .shadow()
            .find('.dropdown-wrapper')
            .find('min-auto-complete')
            .shadow()
            .find('#autocomplete-wrapper')
            .find('.align-items-center')
            .find('.select-control-wrap')
            .find('.editable-input-container')
            .find('#input')
            .type('WHITE')

        //Click option from drop down list
        cy.get('skin-atlas')
            .shadow()
            .find('.wrapper')
            .find('#main')
            .find('private-component')
            .find('informatics-view')
            .shadow()
            .find('.main-content')
            .find('md-tabs')
            .shadow()
            .find('iron-pages')
            .find('.iron-selected')
            .find('clinical-trial')
            .shadow()
            .find('#edc-table')
            .find('edc-information-table')
            .shadow()
            .find('div')
            .find('table-with-action-bar')
            .shadow()
            .find('.table-wrapper')
            .find('md-table')
            .shadow()
            .find('.table-wrapper')
            .find('#filter-menu')
            .find('filter-capsule')
            .shadow()
            .find('.dropdown-wrapper')
            .find('min-auto-complete')
            .shadow()
            .find('#autocomplete-wrapper')
            .find('div')
            .find('iron-dropdown')
            .find('mwc-list')
            .find('mwc-list-item')
            .eq('0')
            .click({forcce:true})

        
        //Click Apply Button
        cy.get('skin-atlas')
            .shadow()
            .find('.wrapper')
            .find('#main')
            .find('private-component')
            .find('informatics-view')
            .shadow()
            .find('.main-content')
            .find('md-tabs')
            .shadow()
            .find('iron-pages')
            .find('.iron-selected')
            .find('clinical-trial')
            .shadow()
            .find('#edc-table')
            .find('edc-information-table')
            .shadow()
            .find('div')
            .find('table-with-action-bar')
            .shadow()
            .find('.table-wrapper')
            .find('md-table')
            .shadow()
            .find('.table-wrapper')
            .find('#filter-menu')
            .find('filter-capsule')
            .shadow()
            .find('.button-wrapper')
            .find('.apply')
            .click()

    }

    FilterHeight()
    {
        //Click Pyramid icon
        cy.get('skin-atlas')
            .shadow()
            .find('.wrapper')
            .find('#main')
            .find('private-component')
            .find('informatics-view')
            .shadow()
            .find('.main-content')
            .find('md-tabs')
            .shadow()
            .find('iron-pages')
            .find('.iron-selected')
            .find('clinical-trial')
            .shadow()
            .find('#edc-table')
            .find('edc-information-table')
            .shadow()
            .find('div')
            .find('table-with-action-bar')
            .shadow()
            .find('.table-wrapper')
            .find('md-table')
            .shadow()
            .find('.table-wrapper')
            .find('table')
            .find('tr')
            .eq('0')
            .find('th')
            .eq('12')
            .find('.th-content')
            .find('span')
            .eq('1')
            .find('mwc-icon-button')
            .shadow()
            .find('.mdc-ripple-upgraded--unbounded')
            .find('.material-icons')
            .scrollIntoView()
            .click()



        //Type Hright in input field
        cy.get('skin-atlas')
        .shadow()
        .find('.wrapper')
        .find('#main')
        .find('private-component')
        .find('informatics-view')
        .shadow()
        .find('.main-content')
        .find('md-tabs')
        .shadow()
        .find('iron-pages')
        .find('.iron-selected')
        .find('clinical-trial')
        .shadow()
        .find('#edc-table')
        .find('edc-information-table')
        .shadow()
        .find('div')
        .find('table-with-action-bar')
        .shadow()
        .find('.table-wrapper')
        .find('md-table')
        .shadow()
        .find('.table-wrapper')
        .find('#filter-menu')
        .find('filter-capsule')
        .shadow()
        .find('.dropdown-wrapper')
        .find('min-input')
        .shadow()
        .find('.form-group')
        .find('.form-group__control-wrap')
        .find('.form-group__input-control')
        .type('71')


        

        
        //Click Apply Button
        cy.get('skin-atlas')
            .shadow()
            .find('.wrapper')
            .find('#main')
            .find('private-component')
            .find('informatics-view')
            .shadow()
            .find('.main-content')
            .find('md-tabs')
            .shadow()
            .find('iron-pages')
            .find('.iron-selected')
            .find('clinical-trial')
            .shadow()
            .find('#edc-table')
            .find('edc-information-table')
            .shadow()
            .find('div')
            .find('table-with-action-bar')
            .shadow()
            .find('.table-wrapper')
            .find('md-table')
            .shadow()
            .find('.table-wrapper')
            .find('#filter-menu')
            .find('filter-capsule')
            .shadow()
            .find('.button-wrapper')
            .find('.apply')
            .click()

    }
    FilterW0PASI()
    {
        //Click Pyramid icon
        cy.get('skin-atlas')
            .shadow()
            .find('.wrapper')
            .find('#main')
            .find('private-component')
            .find('informatics-view')
            .shadow()
            .find('.main-content')
            .find('md-tabs')
            .shadow()
            .find('iron-pages')
            .find('.iron-selected')
            .find('clinical-trial')
            .shadow()
            .find('#edc-table')
            .find('edc-information-table')
            .shadow()
            .find('div')
            .find('table-with-action-bar')
            .shadow()
            .find('.table-wrapper')
            .find('md-table')
            .shadow()
            .find('.table-wrapper')
            .find('table')
            .find('tr')
            .eq('0')
            .find('th')
            .eq('13')
            .find('.th-content')
            .find('span')
            .eq('1')
            .find('mwc-icon-button')
            .shadow()
            .find('.mdc-ripple-upgraded--unbounded')
            .find('.material-icons')
            .scrollIntoView()
            .click()



        //Type Start value of PASI in input field
        cy.get('skin-atlas')
            .shadow()
            .find('.wrapper')
            .find('#main')
            .find('private-component')
            .find('informatics-view')
            .shadow()
            .find('.main-content')
            .find('md-tabs')
            .shadow()
            .find('iron-pages')
            .find('.iron-selected')
            .find('clinical-trial')
            .shadow()
            .find('#edc-table')
            .find('edc-information-table')
            .shadow()
            .find('div')
            .find('table-with-action-bar')
            .shadow()
            .find('.table-wrapper')
            .find('md-table')
            .shadow()
            .find('.table-wrapper')
            .find('#filter-menu')
            .find('filter-capsule')
            .shadow()
            .find('.number-range-wrapper')
            .find('flex-box')
            .find('min-input')
            .eq('0')
            .shadow()
            .find('.form-group')
            .find('.form-group__control-wrap')
            .find('.form-group__input-control')
            .type('1')

        
        //Type End value of PASI in input field
        cy.get('skin-atlas')
            .shadow()
            .find('.wrapper')
            .find('#main')
            .find('private-component')
            .find('informatics-view')
            .shadow()
            .find('.main-content')
            .find('md-tabs')
            .shadow()
            .find('iron-pages')
            .find('.iron-selected')
            .find('clinical-trial')
            .shadow()
            .find('#edc-table')
            .find('edc-information-table')
            .shadow()
            .find('div')
            .find('table-with-action-bar')
            .shadow()
            .find('.table-wrapper')
            .find('md-table')
            .shadow()
            .find('.table-wrapper')
            .find('#filter-menu')
            .find('filter-capsule')
            .shadow()
            .find('.number-range-wrapper')
            .find('flex-box')
            .find('.ml-4x')
            .shadow()
            .find('.form-group')
            .find('.form-group__control-wrap')
            .find('.form-group__input-control')
            .type('10')

        
        
        //Click Apply Button
        cy.get('skin-atlas')
            .shadow()
            .find('.wrapper')
            .find('#main')
            .find('private-component')
            .find('informatics-view')
            .shadow()
            .find('.main-content')
            .find('md-tabs')
            .shadow()
            .find('iron-pages')
            .find('.iron-selected')
            .find('clinical-trial')
            .shadow()
            .find('#edc-table')
            .find('edc-information-table')
            .shadow()
            .find('div')
            .find('table-with-action-bar')
            .shadow()
            .find('.table-wrapper')
            .find('md-table')
            .shadow()
            .find('.table-wrapper')
            .find('#filter-menu')
            .find('filter-capsule')
            .shadow()
            .find('.button-wrapper')
            .find('.apply')
            .click()

    }
    FilterW4PASI()
    {
        //Click Pyramid icon
        cy.get('skin-atlas')
            .shadow()
            .find('.wrapper')
            .find('#main')
            .find('private-component')
            .find('informatics-view')
            .shadow()
            .find('.main-content')
            .find('md-tabs')
            .shadow()
            .find('iron-pages')
            .find('.iron-selected')
            .find('clinical-trial')
            .shadow()
            .find('#edc-table')
            .find('edc-information-table')
            .shadow()
            .find('div')
            .find('table-with-action-bar')
            .shadow()
            .find('.table-wrapper')
            .find('md-table')
            .shadow()
            .find('.table-wrapper')
            .find('table')
            .find('tr')
            .eq('0')
            .find('th')
            .eq('14')
            .find('.th-content')
            .find('span')
            .eq('1')
            .find('mwc-icon-button')
            .shadow()
            .find('.mdc-ripple-upgraded--unbounded')
            .find('.material-icons')
            .scrollIntoView()
            .click()



        //Type Start value of PASI in input field
        cy.get('skin-atlas')
            .shadow()
            .find('.wrapper')
            .find('#main')
            .find('private-component')
            .find('informatics-view')
            .shadow()
            .find('.main-content')
            .find('md-tabs')
            .shadow()
            .find('iron-pages')
            .find('.iron-selected')
            .find('clinical-trial')
            .shadow()
            .find('#edc-table')
            .find('edc-information-table')
            .shadow()
            .find('div')
            .find('table-with-action-bar')
            .shadow()
            .find('.table-wrapper')
            .find('md-table')
            .shadow()
            .find('.table-wrapper')
            .find('#filter-menu')
            .find('filter-capsule')
            .shadow()
            .find('.number-range-wrapper')
            .find('flex-box')
            .find('min-input')
            .eq('0')
            .shadow()
            .find('.form-group')
            .find('.form-group__control-wrap')
            .find('.form-group__input-control')
            .type('1')

        
        //Type End value of PASI in input field
        cy.get('skin-atlas')
            .shadow()
            .find('.wrapper')
            .find('#main')
            .find('private-component')
            .find('informatics-view')
            .shadow()
            .find('.main-content')
            .find('md-tabs')
            .shadow()
            .find('iron-pages')
            .find('.iron-selected')
            .find('clinical-trial')
            .shadow()
            .find('#edc-table')
            .find('edc-information-table')
            .shadow()
            .find('div')
            .find('table-with-action-bar')
            .shadow()
            .find('.table-wrapper')
            .find('md-table')
            .shadow()
            .find('.table-wrapper')
            .find('#filter-menu')
            .find('filter-capsule')
            .shadow()
            .find('.number-range-wrapper')
            .find('flex-box')
            .find('.ml-4x')
            .shadow()
            .find('.form-group')
            .find('.form-group__control-wrap')
            .find('.form-group__input-control')
            .type('10')

        
        
        //Click Apply Button
        cy.get('skin-atlas')
            .shadow()
            .find('.wrapper')
            .find('#main')
            .find('private-component')
            .find('informatics-view')
            .shadow()
            .find('.main-content')
            .find('md-tabs')
            .shadow()
            .find('iron-pages')
            .find('.iron-selected')
            .find('clinical-trial')
            .shadow()
            .find('#edc-table')
            .find('edc-information-table')
            .shadow()
            .find('div')
            .find('table-with-action-bar')
            .shadow()
            .find('.table-wrapper')
            .find('md-table')
            .shadow()
            .find('.table-wrapper')
            .find('#filter-menu')
            .find('filter-capsule')
            .shadow()
            .find('.button-wrapper')
            .find('.apply')
            .click()

    }

    FilterW12PASI()
    {
        //Click Pyramid icon
        cy.get('skin-atlas')
            .shadow()
            .find('.wrapper')
            .find('#main')
            .find('private-component')
            .find('informatics-view')
            .shadow()
            .find('.main-content')
            .find('md-tabs')
            .shadow()
            .find('iron-pages')
            .find('.iron-selected')
            .find('clinical-trial')
            .shadow()
            .find('#edc-table')
            .find('edc-information-table')
            .shadow()
            .find('div')
            .find('table-with-action-bar')
            .shadow()
            .find('.table-wrapper')
            .find('md-table')
            .shadow()
            .find('.table-wrapper')
            .find('table')
            .find('tr')
            .eq('0')
            .find('th')
            .eq('15')
            .find('.th-content')
            .find('span')
            .eq('1')
            .find('mwc-icon-button')
            .shadow()
            .find('.mdc-ripple-upgraded--unbounded')
            .find('.material-icons')
            .scrollIntoView()
            .click()



        //Type Start value of PASI in input field
        cy.get('skin-atlas')
            .shadow()
            .find('.wrapper')
            .find('#main')
            .find('private-component')
            .find('informatics-view')
            .shadow()
            .find('.main-content')
            .find('md-tabs')
            .shadow()
            .find('iron-pages')
            .find('.iron-selected')
            .find('clinical-trial')
            .shadow()
            .find('#edc-table')
            .find('edc-information-table')
            .shadow()
            .find('div')
            .find('table-with-action-bar')
            .shadow()
            .find('.table-wrapper')
            .find('md-table')
            .shadow()
            .find('.table-wrapper')
            .find('#filter-menu')
            .find('filter-capsule')
            .shadow()
            .find('.number-range-wrapper')
            .find('flex-box')
            .find('min-input')
            .eq('0')
            .shadow()
            .find('.form-group')
            .find('.form-group__control-wrap')
            .find('.form-group__input-control')
            .type('1')

        
        //Type End value of PASI in input field
        cy.get('skin-atlas')
            .shadow()
            .find('.wrapper')
            .find('#main')
            .find('private-component')
            .find('informatics-view')
            .shadow()
            .find('.main-content')
            .find('md-tabs')
            .shadow()
            .find('iron-pages')
            .find('.iron-selected')
            .find('clinical-trial')
            .shadow()
            .find('#edc-table')
            .find('edc-information-table')
            .shadow()
            .find('div')
            .find('table-with-action-bar')
            .shadow()
            .find('.table-wrapper')
            .find('md-table')
            .shadow()
            .find('.table-wrapper')
            .find('#filter-menu')
            .find('filter-capsule')
            .shadow()
            .find('.number-range-wrapper')
            .find('flex-box')
            .find('.ml-4x')
            .shadow()
            .find('.form-group')
            .find('.form-group__control-wrap')
            .find('.form-group__input-control')
            .type('10')

        
        
        //Click Apply Button
        cy.get('skin-atlas')
            .shadow()
            .find('.wrapper')
            .find('#main')
            .find('private-component')
            .find('informatics-view')
            .shadow()
            .find('.main-content')
            .find('md-tabs')
            .shadow()
            .find('iron-pages')
            .find('.iron-selected')
            .find('clinical-trial')
            .shadow()
            .find('#edc-table')
            .find('edc-information-table')
            .shadow()
            .find('div')
            .find('table-with-action-bar')
            .shadow()
            .find('.table-wrapper')
            .find('md-table')
            .shadow()
            .find('.table-wrapper')
            .find('#filter-menu')
            .find('filter-capsule')
            .shadow()
            .find('.button-wrapper')
            .find('.apply')
            .click()

    }

    SinglePatientView()
    {
        cy.get('skin-atlas')
            .shadow()
            .find('.wrapper')
            .find('#main')
            .find('private-component')
            .find('informatics-view')
            .shadow()
            .find('.main-content')
            .find('md-tabs')
            .shadow()
            .find('iron-pages')
            .find('.iron-selected')
            .find('clinical-trial')
            .shadow()
            .find('#edc-table')
            .find('edc-information-table')
            .shadow()
            .find('div')
            .find('table-with-action-bar')
            .shadow()
            .find('.table-wrapper')
            .find('md-table')
            .shadow()
            .find('.table-wrapper')
            .find('table')
            .find('tr')
            .eq('1')
            .find('td')
            .eq('0')
            .find('.three-dot-icon')
            .shadow()
            .find('.mdc-ripple-upgraded--unbounded')
            .find('.material-icons')
            .click()

        cy.get('skin-atlas')
            .shadow()
            .find('.wrapper')
            .find('#main')
            .find('private-component')
            .find('informatics-view')
            .shadow()
            .find('.main-content')
            .find('md-tabs')
            .shadow()
            .find('iron-pages')
            .find('.iron-selected')
            .find('clinical-trial')
            .shadow()
            .find('#edc-table')
            .find('edc-information-table')
            .shadow()
            .find('div')
            .find('table-with-action-bar')
            .shadow()
            .find('.table-wrapper')
            .find('md-table')
            .shadow()
            .find('.table-wrapper')
            .find('#row-menu')
            .find('mwc-list')
            .find('.dropdown')
            .click({force:true})           
            
    }

    AssertingSinglePatientView()
    {
        cy.get('skin-atlas')
            .shadow()
            .find('.wrapper')
            .find('#main')
            .find('private-component')
            .find('study-patient-view')
            .shadow()
            .find('nav-bar')
            .shadow()
            .find('.navbar-wrapper')
            .find('.nav-bar-title')
            .should('be.visible')
            .contains('Study Patient View')

    }


        
        
        


           




}
export default Informatics
