class Manufacture
{
    Manufacturing()
    {
        cy.get('skin-atlas')
            .shadow()
            .find('.wrapper')
            .find('#main')
            .find('private-component')
            .shadow()
            .find('side-bar')
            .shadow()
            .find('.sidebar-main-wrapper')
            .find('.sidebar-inner-wrapper')
            .find('.menu-item')
            .eq('2')
            .click()
            .wait(5000)
        cy.waitUntil(() => 
        cy.get('skin-atlas')
            .shadow()
            .find('.wrapper')
            .find('#main')
            .find('private-component')
            .find('manufacturing-view')
            .shadow()
            .find('nav-bar')
            .shadow()
            .find('.navbar-wrapper')
            .find('.nav-bar-title')
            .contains('Manufacturing'), {

            errorMsg: 'Could not find title', // overrides the default error message
            timeout: 3000, // waits up to 2000 ms, default to 5000
            interval: 500 // performs the check every 500 ms, default to 200
            });



    }

    FilterPartName()
    {      
        //Click Pyramid icon for Part Name filter
        cy.get('skin-atlas')
            .shadow()
            .find('.wrapper')
            .find('#main')
            .find('private-component')
            .find('manufacturing-view')
            .shadow()
            .find('.main-content')
            .find('manufacture-table')
            .shadow()
            .find('table-with-action-bar')
            .shadow()
            .find('.table-wrapper')
            .find('md-table')
            .shadow()
            .find('paper-card')
            .find('table')
            .find('tr')
            .find('th')
            .eq('1')
            .find('.th-content')
            .find('span')
            .eq('1')
            .find('mwc-icon-button')
            .shadow()
            .find('.mdc-ripple-upgraded--unbounded')
            .click()
           
            
        
        //Select Drop down icon 
        cy.get('skin-atlas')
            .shadow()
            .find('.wrapper')
            .find('#main')
            .find('private-component')
            .find('manufacturing-view')
            .shadow()
            .find('.main-content')
            .find('manufacture-table')
            .shadow()
            .find('table-with-action-bar')
            .shadow()
            .find('.table-wrapper')
            .find('md-table')
            .shadow()
            .find('paper-card')
            .find('overlay-menu-wrap')            
            .find('filter-capsule')
            .shadow()
            .find('.dropdown-wrapper')
            .find('min-auto-complete')
            .shadow()
            .find('#autocomplete-wrapper')
            .find('.align-items-center')
            .find('.select-control-wrap')
            .find('.chevron')
            .click()

        //Select Part name from dropdown list
        cy.get('skin-atlas')
            .shadow()
            .find('.wrapper')
            .find('#main')
            .find('private-component')
            .find('manufacturing-view')
            .shadow()
            .find('.main-content')
            .find('manufacture-table')
            .shadow()
            .find('table-with-action-bar')
            .shadow()
            .find('.table-wrapper')
            .find('md-table')
            .shadow()
            .find('paper-card')
            .find('overlay-menu-wrap')
            .find('filter-capsule')
            .shadow()
            .find('.dropdown-wrapper')
            .find('min-auto-complete')
            .shadow()
            .find('#autocomplete-wrapper')
            .find('div')
            .find('iron-dropdown')
            .find('mwc-list')
            .find('mwc-list-item')
            .eq('3')
            .click()
        
        //Click apply button
        cy.get('skin-atlas')
            .shadow()
            .find('.wrapper')
            .find('#main')
            .find('private-component')
            .find('manufacturing-view')
            .shadow()
            .find('.main-content')
            .find('manufacture-table')
            .shadow()
            .find('table-with-action-bar')
            .shadow()
            .find('.table-wrapper')
            .find('md-table')
            .shadow()
            .find('paper-card')
            .find('overlay-menu-wrap')
            .find('filter-capsule')
            .shadow()
            .find('.button-wrapper')
            .find('.apply')
            .click()

        
    }   
    
    FilterCustomerName()
    {      
        //Click Pyramid icon for Customer Name filter
        cy.get('skin-atlas')
            .shadow()
            .find('.wrapper')
            .find('#main')
            .find('private-component')
            .find('manufacturing-view')
            .shadow()
            .find('.main-content')
            .find('manufacture-table')
            .shadow()
            .find('table-with-action-bar')
            .shadow()
            .find('.table-wrapper')
            .find('md-table')
            .shadow()
            .find('paper-card')
            .find('table')
            .find('tr')
            .find('th')
            .eq('2')
            .find('.th-content')
            .find('span')
            .eq('1')
            .find('mwc-icon-button')
            .shadow()
            .find('.mdc-ripple-upgraded--unbounded')
            .click()

        //Select Drop down icon 
        cy.get('skin-atlas')
            .shadow()
            .find('.wrapper')
            .find('#main')
            .find('private-component')
            .find('manufacturing-view')
            .shadow()
            .find('.main-content')
            .find('manufacture-table')
            .shadow()
            .find('table-with-action-bar')
            .shadow()
            .find('.table-wrapper')
            .find('md-table')
            .shadow()
            .find('paper-card')
            .find('overlay-menu-wrap')            
            .find('filter-capsule')
            .shadow()
            .find('.dropdown-wrapper')
            .find('min-auto-complete')
            .shadow()
            .find('#autocomplete-wrapper')
            .find('.align-items-center')
            .find('.select-control-wrap')
            .find('.editable-input-container')
            .find('#input')
            .click()

        //Select Customer name from dropdown list
        cy.get('skin-atlas')
            .shadow()
            .find('.wrapper')
            .find('#main')
            .find('private-component')
            .find('manufacturing-view')
            .shadow()
            .find('.main-content')
            .find('manufacture-table')
            .shadow()
            .find('table-with-action-bar')
            .shadow()
            .find('.table-wrapper')
            .find('md-table')
            .shadow()
            .find('paper-card')
            .find('overlay-menu-wrap')
            .find('filter-capsule')
            .shadow()
            .find('.dropdown-wrapper')
            .find('min-auto-complete')
            .shadow()
            .find('#autocomplete-wrapper')
            .find('div')
            .find('iron-dropdown')
            .find('mwc-list')
            .find('mwc-list-item')
            .eq('4')
            .click()
        
        //Click apply button
        cy.get('skin-atlas')
            .shadow()
            .find('.wrapper')
            .find('#main')
            .find('private-component')
            .find('manufacturing-view')
            .shadow()
            .find('.main-content')
            .find('manufacture-table')
            .shadow()
            .find('table-with-action-bar')
            .shadow()
            .find('.table-wrapper')
            .find('md-table')
            .shadow()
            .find('paper-card')
            .find('overlay-menu-wrap')
            .find('filter-capsule')
            .shadow()
            .find('.button-wrapper')
            .find('.apply')
            .click()       
            
    }
   
       
 
    FilterDate()
    {
        //Click Pyramid icon for Date filter
        cy.get('skin-atlas')
            .shadow()
            .find('.wrapper')
            .find('#main')
            .find('private-component')
            .find('manufacturing-view')
            .shadow()
            .find('.main-content')
            .find('manufacture-table')
            .shadow()
            .find('table-with-action-bar')
            .shadow()
            .find('.table-wrapper')
            .find('md-table')
            .shadow()
            .find('paper-card')
            .find('table')
            .find('tr')
            .find('th')
            .eq('6')
            .find('.th-content')
            .find('span')
            .eq('1')
            .find('mwc-icon-button')
            .shadow()
            .find('.mdc-ripple-upgraded--unbounded')
            .click()

        //Select Start Date input field
        cy.get('skin-atlas')
            .shadow()
            .find('.wrapper')
            .find('#main')
            .find('private-component')
            .find('manufacturing-view')
            .shadow()
            .find('.main-content')
            .find('manufacture-table')
            .shadow()
            .find('table-with-action-bar')
            .shadow()
            .find('.table-wrapper')
            .find('md-table')
            .shadow()
            .find('paper-card')
            .find('overlay-menu-wrap')
            .find('filter-capsule')
            .shadow()
            .find('.relative')
            .find('.date-range-wrapper')
            .find('md-date-picker')
            .shadow()
            .find('vaadin-date-picker')
            .shadow()
            .find('vaadin-date-picker-text-field')
            .shadow()
            .find('.vaadin-text-field-container')
            .find('div')
            .find('[name=input]')
            .find('[name=startDate]')
            .click()                  
           
        //Select Start Date
        cy.get('vaadin-date-picker-overlay')
            .shadow()
            .find('#overlay')
            .find('#content')
            .shadow()
            .find('vaadin-date-picker-overlay-content')
            .shadow()
            .find('#scrollers')
            .find('#monthScroller')
            .find('div')
            .eq('0')
            .find('vaadin-month-calendar')
            .shadow()
            .find('#monthGrid')
            .find('#days-container')
            .find('#days')
            .find('div')
            .eq('1')
            .click({force:true})
            .click({force:true})
            .wait(2000)
                        

        //Select End Date Input field
        cy.get('skin-atlas')
            .shadow()
            .find('.wrapper')
            .find('#main')
            .find('private-component')
            .find('manufacturing-view')
            .shadow()
            .find('.main-content')
            .find('manufacture-table')
            .shadow()
            .find('table-with-action-bar')
            .shadow()
            .find('.table-wrapper')
            .find('md-table')
            .shadow()
            .find('paper-card')
            .find('overlay-menu-wrap')
            .find('filter-capsule')
            .shadow()
            .find('.relative')
            .find('.date-range-wrapper')
            .find('md-date-picker')
            .eq('1')
            .shadow()
            .find('vaadin-date-picker')
            .shadow()
            .find('vaadin-date-picker-text-field')
            .shadow()
            .find('.vaadin-text-field-container')
            .find('div')
            .find('[name=input]')
            .find('[name=endDate]')
            .click()

        //Select End Date
        cy.get('vaadin-date-picker-overlay')
            .shadow()
            .find('#overlay')
            .find('#content')
            .shadow()
            .find('vaadin-date-picker-overlay-content')
            .shadow()
            .find('[role=toolbar]')
            .find('#todayButton')
            .shadow()
            .find('#button')
            .click({force:true})
            .wait(3000)

        //Apply button for Date filter
        cy.get('skin-atlas')
            .shadow()
            .find('.wrapper')
            .find('#main')
            .find('private-component')
            .find('manufacturing-view')
            .shadow()
            .find('.main-content')
            .find('#manufacture-table')
            .shadow()
            .find('div')
            .find('table-with-action-bar')
            .shadow()
            .find('.table-wrapper')
            .find('md-table')
            .shadow()
            .find('.table-wrapper')
            .find('#date-filter-menu')
            .find('filter-capsule')
            .shadow()
            .find('.button-wrapper')
            .find('.apply')
            .click()
        
        //Asserting PartName Filter
        cy.get('skin-atlas')
            .shadow()
            .find('.wrapper')
            .find('#main')
            .find('private-component')
            .find('manufacturing-view')
            .shadow()
            .find('.main-content')
            .find('manufacture-table')
            .shadow()
            .find('table-with-action-bar')
            .shadow()
            .find('.table-wrapper')
            .find('md-table')
            .shadow()
            .find('.justify-between')
            .find('filter-apply-block')
            .shadow()
            .find('.content')
            .eq('0')
            .find('colored-tag')
            .contains('Part Name')

        //Asserting CustomerName Filter
        cy.get('skin-atlas')
            .shadow()
            .find('.wrapper')
            .find('#main')
            .find('private-component')
            .find('manufacturing-view')
            .shadow()
            .find('.main-content')
            .find('manufacture-table')
            .shadow()
            .find('table-with-action-bar')
            .shadow()
            .find('.table-wrapper')
            .find('md-table')
            .shadow()
            .find('.justify-between')
            .find('filter-apply-block')
            .shadow()
            .find('.content')
            .eq('1')
            .find('colored-tag')
            .contains('Customer Name')

        //Asserting DateStart Filter
        cy.get('skin-atlas')
            .shadow()
            .find('.wrapper')
            .find('#main')
            .find('private-component')
            .find('manufacturing-view')
            .shadow()
            .find('.main-content')
            .find('manufacture-table')
            .shadow()
            .find('table-with-action-bar')
            .shadow()
            .find('.table-wrapper')
            .find('md-table')
            .shadow()
            .find('.justify-between')
            .find('filter-apply-block')
            .shadow()
            .find('.content')
            .eq('2')
            .find('colored-tag')
            .contains('Date Start')

            

        

        

        }
     
}

export default Manufacture
